services:
  web:
    build: .
    volumes:
      - .:/app
      - ./chinook.db:/app/chinook.db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: unless-stopped